### ISSUE TITLE
Unknown filter "matchall", hence option "action" is unparsable

### ISSUE THREAD

**Issue by marsex** [cryzed/TrafficToll#3] opened 2019-08-14 07:33 UTC
error
```
root@mc:~# sudo tt eth0 limit.yaml --delay 0.5
2019-08-14 04:26:19.201 | INFO     | traffictoll.cli:main:48 - Setting up global download limiter with max rate 10kbps
2019-08-14 04:26:19.202 | INFO     | traffictoll.cli:main:50 - Setting up global upload limiter with max rate 1kbps
Unknown filter "matchall", hence option "action" is unparsable
Unknown filter "matchall", hence option "flowid" is unparsable
Unknown filter "matchall", hence option "flowid" is unparsable

```

limit.yaml
```
# Global limits
download: 500kbps
upload: 100kbps
```

**Comment by cryzed** [comment] 2019-08-14 13:44
What version of Linux / iproute2 are you running? Please try `$ pip install https://github.com/cryzed/TrafficToll/archive/develop.zip` and see if that works for you.

**Comment by cryzed** [comment] 2019-08-16 12:12
@marsex any updates? Otherwise I'm closing this issue.

**Comment by marsex** [comment] 2019-08-16 21:11
iproute 4.4 (how do i check the version?), slackware 14.2.
i tried it and it gave me the same error

**Comment by cryzed** [comment] 2019-08-16 21:55
It shouldn't have given you the same error, please try running:

`$ pip install https://github.com/cryzed/TrafficToll/archive/develop.zip --upgrade`

And then try again. The problem is that you are seemingly using very old packages, the `matchall` filter has been around for a long time.

**Comment by marsex** [comment] 2019-08-17 01:26
got it. its working!

**Comment by cryzed** [comment] 2019-08-17 19:47
Great to hear, I'll merge this into master then.

**Closed as completed by cryzed** 2019-08-17 19:47 UTC
Labels: bug, enhancement
